packages/zefyr/lib/src/widgets/editable_text_block.dart
packages/zefyr/pubspec.yaml

数字つきリストのデザイン修正

---

packages/zefyr/lib/src/widgets/editable_text_block.dart

https://github.com/hokutoresident/zefyr/pull/15 で修正したものが原因で上にずれていた
確認時に再現しなかったのが謎

リストの黒丸の位置修正

---

packages/zefyr/lib/src/widgets/editor.dart

scrollable = falseの時に処理が動いてなかったのが原因なので、その場合もpaddingをつける
https://www.notion.so/hokuto/5e402562ed614fe691150b7ac8bc9c70?v=63bd086124a64e54902fc92e27d2e7ea&p=c533b03a639a4023afd4995e232e0424

hokuto appの方で余白タップでの改行が動いてない

---

packages/zefyr/lib/src/widgets/controller.dart
packages/zefyr/lib/src/widgets/editor.dart
packages/zefyr/test/widgets/controller_test.dart

- 以下のPRで、scrollable == falseの時に`overflowed by xxx px`のエラーが出てスクロールできなくなってた問題を修正
- 最後が改行の時はそこにカーソル当たるようにした
- テストケース追加
https://www.notion.so/hokuto/5e402562ed614fe691150b7ac8bc9c70?v=63bd086124a64e54902fc92e27d2e7ea&p=b80fc23b05304b4390e28ff2c2f7e2a5
https://github.com/hokutoresident/zefyr/pull/20
https://github.com/hokutoresident/zefyr/pull/21

hokuto appの方で余白タップでの改行が動いてない 

---

packages/zefyr/lib/src/widgets/editable_text_block.dart
packages/zefyr/lib/src/widgets/editor.dart
packages/zefyr/lib/src/widgets/theme.dart

- [H2タイトルの上余白が16pt⇒32px にする＋Slackでの指摘](https://www.notion.so/hokuto/H2-16pt-32px-Slack-53e4b61e01334ca4b2767cd1270d9b27)
| before | after |
| -- | -- |
| <image src="https://user-images.githubusercontent.com/55462291/124550016-00219580-de6b-11eb-8677-2ffd2c5f121b.png" width="250"> | <image src="https://user-images.githubusercontent.com/55462291/124549872-c18bdb00-de6a-11eb-92e8-f66df8c88db9.png" width="250"> |
| before | after |
| -- | -- |
| <image src="https://user-images.githubusercontent.com/55462291/124550048-0e6fb180-de6b-11eb-9e98-eab4466b5faa.png" width="250"> | <image src="https://user-images.githubusercontent.com/55462291/124549901-d0728d80-de6a-11eb-9958-4aa039ef8ea3.png" width="250"> |

H2タイトルの上余白が16pt⇒32px にする＋Slackでの指摘

---

packages/zefyr/example/ios/Podfile.lock
packages/zefyr/lib/src/widgets/controller.dart
packages/zefyr/lib/src/widgets/editor_selection_delegate_mixin.dart
packages/zefyr/pubspec.yaml

URLは打ち込んだりペーストしてもオートリンクの`AutoFormatLinksRule`は走らなく、最後尾にスペースを一度入れたときにオートリンク処理が発火する
また、`AutoFormatLinksRule`の中で文字自体の加工などはできないので、replaceTextでペーストした直後に追加でスペースを入れている
https://user-images.githubusercontent.com/34063746/125184495-4b67e980-e259-11eb-9112-2a2db45d2ca6.mov
https://www.notion.so/hokuto/5e402562ed614fe691150b7ac8bc9c70?v=9acbd05cb1b94d879da17ea1fe793f97&p=7046a91405394c3d8a64fee1459d7afa

URL入力時は自動でリンク化

---

packages/zefyr/lib/src/rendering/editable_text_line.dart
packages/zefyr/lib/src/widgets/editor.dart
packages/zefyr/lib/src/widgets/theme.dart

- [囲み枠､各スタイルのデザイン修正](https://www.notion.so/hokuto/6c8150ca8fdf431d8b2ab3bf9949cf7b)
* 見出し：デザインを完璧に再現するのが難しそうだったので、上下のパディングが無い状態でも問題ないか確認中です。
* もし、見出しに上下のPaddingを付ける方法をご存知の方がいらっしゃいましたら、教えて頂けると助かります。
| 囲み枠 | マーカー |
| -- | -- |
| <image src="https://user-images.githubusercontent.com/55462291/126903883-f4bc432e-486c-40b0-a536-847059f51d78.png" width="250"> | <image src="https://user-images.githubusercontent.com/55462291/126903862-3e2a1661-de0c-4a1e-8673-44c153f6a4ab.png" width="250"> |
| 注釈 | 見出し |
| -- | -- |
| <image src="https://user-images.githubusercontent.com/55462291/126903910-ffc3c224-8e0b-4c30-86ad-cd7b1bb40675.png" width="250"> | <image src="https://user-images.githubusercontent.com/55462291/126904065-428a3dcf-6059-40d8-b494-b0493bbbc02f.png" width="250"> |

囲み枠､各スタイルのデザイン修正

---

packages/zefyr/lib/src/widgets/theme.dart

flutterのデフォルトフォントであるrobotoをfigmaで使用してるnotosansを全体に適用しました
https://www.notion.so/hokuto/5e402562ed614fe691150b7ac8bc9c70?v=9acbd05cb1b94d879da17ea1fe793f97&p=a00f33ac6c3e407db18b702563f663d3
|before|after|
|-|-|
|<img width="340" alt="Screen Shot 2021-08-21 at 15 25 28" src="https://user-images.githubusercontent.com/34063746/130312998-eadada50-56cd-46a0-ba8e-1db9094a9dca.png">|<img width="353" alt="Screen Shot 2021-08-21 at 15 19 24" src="https://user-images.githubusercontent.com/34063746/130312989-f7732d4a-fe37-4578-8d47-47b1846d55be.png">|

全角半角混じった文字列に対してマーカー・下線を引くと線がガタついてた問題の修正

---

packages/zefyr/lib/src/widgets/controller.dart

`AutoExitBlockRule`はblock要素に2連続で`\n`が来たときにスタイルを抜ける。
それを発動させるために`NotusAttribute.largeHeading, NotusAttribute.middleHeading, NotusAttribute.bq`内で改行したときは更にもう一度改行することで`AutoExitBlockRule`をトリガーし、スタイルを抜けるようにしてます。
`AutoExitBlockRule`をいじるのがより直接的な解決法ですが、そちらで実現できなかったのでこのアプローチでやってます
https://www.notion.so/hokuto/5e402562ed614fe691150b7ac8bc9c70?v=9acbd05cb1b94d879da17ea1fe793f97&p=c5c3cb3d5f644498873bbecb3f326242
https://user-images.githubusercontent.com/34063746/130315886-aa303935-dc79-424e-b212-277aa1a8921c.mov

見出しと小見出しと注釈が改行時にスタイル残っちゃう

---

packages/zefyr/lib/src/widgets/editor.dart

`selectPositionAt`を治すのは骨が折れそうだったので正常に動いている`selectWord`を代用しました
https://www.notion.so/hokuto/5e402562ed614fe691150b7ac8bc9c70?v=9acbd05cb1b94d879da17ea1fe793f97&p=30d6c86a05564b428df728420ca5c638
https://user-images.githubusercontent.com/34063746/131204074-ddc38904-4a8f-49b4-8895-43e8f77dd3f8.mov

ノートの一部選択がダブルタップでしか出来ないので長押しで一部選択できるようにしたい

---

packages/zefyr/lib/src/widgets/editor.dart

一行目＆＆lh, mhのときにだけ余白がデザイン通りではなかった問題修正
https://www.notion.so/hokuto/5e402562ed614fe691150b7ac8bc9c70?v=9acbd05cb1b94d879da17ea1fe793f97&p=c34861c430d64eedb63cd8322477d0fe
|before|after|
|-|-|
|![Simulator Screen Shot - iPhone 12 Pro - 2021-08-28 at 15 51 08](https://user-images.githubusercontent.com/34063746/131209340-764d2e3e-2101-4173-824c-f2cdec48e3e7.png)|![Simulator Screen Shot - iPhone 12 Pro - 2021-08-28 at 15 48 39](https://user-images.githubusercontent.com/34063746/131209279-1093bd3e-a009-4df2-9c44-688ea59bd2dd.png)|

一行目から二行目にかけての行間だけなにやらおかしいですね。狭い。二行目以降は大丈夫なようです。

---

packages/notus/lib/src/document/attributes.dart

- webでつくったマーカーや文字色にカーソルを置いてもスタイルのボタンが活性にならない問題の修正
- 原因はWebとAppのhexの値が違うこと(#があったりなかったり)で、この差によってmarker/textcolorと同一ではないと判定されていた。
- hexの同一性は判定しないようにした
- 将来的に複数色の指定などもできるようになると思うので、その対応にもなっている
https://www.notion.so/hokuto/5e402562ed614fe691150b7ac8bc9c70?v=9acbd05cb1b94d879da17ea1fe793f97&p=66b11907ec4d4095adec86452aa05548

ノート機能で元々マーカー引かれてるところを選択して、マーカー消そうとしても1回目は消えない。2回目で消える。

---

packages/zefyr/example/lib/src/home.dart
packages/zefyr/lib/src/widgets/controller.dart
packages/zefyr/lib/src/widgets/editor.dart

- app側実装のための子PRです
- 検索合計ヒット数と現在のフォーカスindexの表示
- 画面外にあった場合はスクロール
- colapse状態になったselectionでないとoffset計算ができずスクロールできないので、一旦は単語の右端のみにカーソルを当てている
- ループするようにしてます
https://user-images.githubusercontent.com/34063746/139379825-04516345-63ae-4068-beb0-158ef30334b3.mov
https://www.notion.so/hokuto/5e402562ed614fe691150b7ac8bc9c70?v=9acbd05cb1b94d879da17ea1fe793f97&p=f7da2c323c5f401cba07f175128c1aa3

検索時、該当キーワードがハイライトされているところまで飛ばす

---

packages/zefyr/lib/src/widgets/controller.dart

lh, mh, bqからスタイルを抜ける際、現在カーソルのあたってる一個右のスタイルがlh, mh, bqではない　という条件を足した
https://www.notion.so/hokuto/5e402562ed614fe691150b7ac8bc9c70?v=9acbd05cb1b94d879da17ea1fe793f97&p=660e872ff5a44ebe8dcbc38de928f256
https://user-images.githubusercontent.com/34063746/139535540-41c18910-445b-4eed-9a77-bb2d56cd2e64.mov

見出し内で改行するとフリーズする不具合の修正

---

packages/zefyr/example/ios/Podfile.lock
packages/zefyr/example/lib/src/home.dart
packages/zefyr/lib/src/rendering/editor.dart
packages/zefyr/lib/src/widgets/controller.dart
packages/zefyr/lib/src/widgets/editable_text_block.dart
packages/zefyr/lib/src/widgets/editor.dart
packages/zefyr/lib/src/widgets/text_line.dart

- 現状、編集カーソルを使ってスクロールを実現しているが、誤タップによって思いがけない改変を誘発させたり改行ボタンで次の語句にジャンプできない(編集カーソルのため、そのままノートを編集してしまう)という課題がある
- 検索でジャンプするときはマージンが小さすぎてその単語の次の行の文までよめず、結局手動でスクロールする必要がある
- 編集カーソルの代わりに、`searchFocus`を`TextLine`に渡し、ハイライトの濃淡で検索カーソルを実装した
- カーソルを移動させる時、対象が画面外にある場合は自動でそこにスクロールするようにした
- リファクタ
- `ZefyrEditor`から`searchQuery`と`searchFocus`を変数として渡して外から更新していたのを、`search(String query)`からcontrollerに`searchQuery`を保持してそこからstreamでeditorに渡すようにして検索できるようにした
- 同じように`selectXxxSearchHit()`も変更した
https://user-images.githubusercontent.com/34063746/143772155-fde34866-3d34-4d4c-afe8-1a4634b8dd8d.mov
- [ノート内検索時に編集カーソルの代わりに独自実装の検索カーソルに置き換える](https://www.notion.so/hokuto/5e402562ed614fe691150b7ac8bc9c70?v=090b35774add4b41b6825a1900212710&p=a40ef2dcbd5545a08f8ac5bbe264614d)
- [ノート内検索P2: …

編集カーソル(`ZefyrController.selection`)を使わずにハイライトの濃淡で検索時のカーソルを実装し直す

---

packages/zefyr/lib/util.dart
packages/zefyr/pubspec.yaml
packages/zefyr/test/util_test.dart

https://www.notion.so/hokuto/5e402562ed614fe691150b7ac8bc9c70?v=090b35774add4b41b6825a1900212710&p=349af2f66a944142b2b0bb7bd965721c
https://user-images.githubusercontent.com/34063746/144077807-389453ed-de19-4e19-8a60-06549baf8e95.mov

ひらがな・カタカナを無視して検索ヒットするように

---

packages/zefyr/example/ios/Podfile.lock
packages/zefyr/lib/src/widgets/controller.dart
packages/zefyr/lib/src/widgets/editor.dart

- app側で`Bad state: Stream has already been listened to.`が起きていたので`close()`をつけた
- `.broadcast()`に変更

onChangeSearchQuery, onChangeSearchFocusのlistenerのclose忘れ

---

packages/zefyr/lib/src/widgets/controller.dart
packages/zefyr/lib/src/widgets/editable_text_block.dart
packages/zefyr/lib/src/widgets/editable_text_line.dart
packages/zefyr/lib/src/widgets/editor.dart

ノートがグレーアウトする場合の例外をキャッチしたい
- `ZefyrController` に例外をキャッチして流す `StreamController` を追加
- Deltaが不正な場合に例外が発生する`EditableTextLine`のmountメソッドで例外をキャッチ
- [ノートでグレーアウトする時にエラーメッセージを表示するようにするとともに、エラーログを飛ばすようにする](https://www.notion.so/hokuto/54730fdf9a384a599c8e266233cc81e7)

feat: add ui exception stream to controller

---

packages/zefyr/lib/src/rendering/editable_text_line.dart

Hiragino に変更した影響で調整が必要になったため
iOSでブロックのオフセットを指定
- 全般的に -2
- 引用ブロックで -3
|h1|h2|
|--|--|
|<img width="334" alt="CleanShot 2022-06-27 at 13 11 11@2x" src="https://user-images.githubusercontent.com/10044588/175859334-74157d3c-852b-42da-b5cf-00bf7209c466.png">|<img width="334" src="https://user-images.githubusercontent.com/10044588/175859337-bd598323-dbb4-40f4-a316-6c4d1e8de1b6.png">|
|<img width="334" src="https://user-images.githubusercontent.com/10044588/175859339-627137e8-71aa-41d7-a143-ff6406c57ef6.png">|<img width="334" src="https://user-images.githubusercontent.com/10044588/175859342-57d77260-2be6-4b7b-8c0b-cd07d5914353.png">|

style: ブロックのy方向のオフセットを調整

---

.fvm/flutter_sdk
.gitignore
.vscode/settings.json
packages/zefyr/example/android/app/build.gradle
packages/zefyr/example/android/app/src/main/AndroidManifest.xml
packages/zefyr/example/android/build.gradle
packages/zefyr/example/android/gradle/wrapper/gradle-wrapper.properties

いくつかの設定が古いままだったため
VSCode の設定に fvm のパスを設定

chore: Android で Flutter 3 で zefyr/example をビルドできるように

---

.fvm/flutter_sdk
.gitignore
.vscode/settings.json
packages/zefyr/example/android/app/build.gradle
packages/zefyr/example/android/app/src/main/AndroidManifest.xml
packages/zefyr/example/android/build.gradle
packages/zefyr/example/android/gradle/wrapper/gradle-wrapper.properties
packages/zefyr/lib/src/widgets/editor_selection_delegate_mixin.dart
packages/zefyr/lib/src/widgets/text_selection.dart

テキストの選択範囲の変更時に呼ばれるメソッドが実装されていなかったため、選択範囲の変更が反映されていなかった
- userUpdateTextEditingValue を実装 aa841cf1515d8234cadb1ca8a416c6deac07b2f5
選択範囲の長さが0またはマイナスになったときの挙動が怪しい
- 選択範囲の長さが最低1になるように変更 59a126a6e06bd8e222307d18a0fa47824135f961
- ベストの挙動ではないかもしれませんが、一旦これで……
|before|after|
|--|--|
|https://user-images.githubusercontent.com/10044588/177236319-6845776c-04b7-4650-8af7-01c7b62ae014.mp4|https://user-images.githubusercontent.com/10044588/177236335-03418698-1f83-4bb0-8215-ebf4149d74f9.mp4|

[After #95] fix: テキストの選択範囲が変更できない不具合を修正

---

.fvm/flutter_sdk
.gitignore
.vscode/settings.json
packages/zefyr/example/android/app/build.gradle
packages/zefyr/example/android/app/src/main/AndroidManifest.xml
packages/zefyr/example/android/build.gradle
packages/zefyr/example/android/gradle/wrapper/gradle-wrapper.properties
packages/zefyr/example/pubspec.yaml
packages/zefyr/lib/src/widgets/editor_selection_delegate_mixin.dart
packages/zefyr/lib/src/widgets/text_line.dart
packages/zefyr/lib/src/widgets/text_selection.dart
packages/zefyr/lib/src/widgets/theme.dart

フォント変更に伴なって、Androidで一部特殊文字が文字化けしていたため
- baseStyle に fontFallback を設定 b1eedfe0397234401a8410632bce8e1a57804d4b
- （おまけ）zefyr/example で Noto Sans JP を使えるように設定 1b98a74ea535395fa95e0e6e5b0d7617e9dc2ce9
|before|after|
|--|--|
|![CleanShot 2022-07-05 at 12 38 11@2x](https://user-images.githubusercontent.com/10044588/177244978-e929296a-95ab-4a0e-abc4-b5812ba76c6f.png)|![CleanShot 2022-07-05 at 12 34 41@2x](https://user-images.githubusercontent.com/10044588/177244987-59312012-c19f-4947-9d87-85ba99c1f93a.png)|

[After #96] fix: android font fallback

---

.github/workflows/test_zefyr.yml
packages/zefyr/.fvm/fvm_config.json
packages/zefyr/lib/src/widgets/editor.dart

- [riverpod v2 対応](https://www.notion.so/hokuto/riverpod-v2-ea84c194f8114dad8e3e1af541acc8ca)
- Riverpod v2の恩恵をフルに受けるにはFlutterのバージョンを更新する必要がある
- Flutterのバージョンを更新するにはzefyrに修正が必要
TextInputClientにoverrideが必要なメソッドが増えたので、追加
🙅
🙅

Override new functions in TextInputClient

---

.github/workflows/test_zefyr.yml
packages/zefyr/.fvm/fvm_config.json
packages/zefyr/example/ios/Podfile
packages/zefyr/example/ios/Podfile.lock
packages/zefyr/example/lib/src/editor_page.dart
packages/zefyr/example/lib/src/full_page.dart
packages/zefyr/example/lib/src/home.dart
packages/zefyr/example/lib/src/layout.dart
packages/zefyr/example/lib/src/loading.dart
packages/zefyr/example/lib/src/scaffold.dart
packages/zefyr/example/lib/src/settings.dart
packages/zefyr/example/lib/src/text_field_page.dart
packages/zefyr/example/pubspec.yaml
packages/zefyr/lib/src/widgets/editor.dart
packages/zefyr/lib/src/widgets/theme.dart
packages/zefyr/pubspec.yaml

- Override new functions in TextInputClient
- Declare func type that remove from the framework (`DragSelectionUpdateCallback`)
- Modify according to of and maybeOf naming rules (`ZefyrThemeData`)

Migrate to Flutter 3.10

---

packages/zefyr/lib/src/widgets/editor.dart

[Zefyrの一番上はマージン固定する](https://www.notion.so/hokuto/024955dda9a342f9a438112903ab4ce2?p=140d439c6436480e8082a485fa117d58&pm=s)
|h1|h2|h3|image|
|-|-|-|-|
|![Simulator Screenshot - iPhone 14 - 2023-07-31 at 13 38 57](https://github.com/hokutoresident/zefyr/assets/34063746/f2feb417-251a-4c6b-9b15-204d41a9a936)|![Simulator Screenshot - iPhone 14 - 2023-07-31 at 13 39 01](https://github.com/hokutoresident/zefyr/assets/34063746/cd926ea8-a26e-4404-81c6-416eceaef378)|![Simulator Screenshot - iPhone 14 - 2023-07-31 at 13 39 03](https://github.com/hokutoresident/zefyr/assets/34063746/2d387f95-8b6f-4934-962c-283d5117a702)|![Simulator Screenshot - iPhone 14 - 2023-07-31 at 13 39 15](https://github.com/hokutoresident/zefyr/assets/34063746/04ef3d6a-8479-4c77-88a3-b812d3f45d99)|

一番上だったらどんなstyleでもトップはデフォルトスペースで固定

---

packages/zefyr/lib/src/widgets/editor.dart

１行目の時、見出しの下のスペースが小さくなっていたので、既存と合わせた
|before|after|
|-|-|
|![Simulator Screenshot - iPhone 14 - 2023-12-04 at 19 07 31](https://github.com/hokutoresident/zefyr/assets/34063746/4f3845f9-56e6-4afa-a37f-148ea7f6ed0e)|![Simulator Screenshot - iPhone 14 - 2023-12-04 at 19 07 04](https://github.com/hokutoresident/zefyr/assets/34063746/98ed7a93-6f01-4563-b256-b5cbfaddcc45)|

１行目の見出しのスペース修正

---

packages/zefyr/lib/src/widgets/controller.dart

(どうやって該当するノートを作るのかはわかっていないが、) isEndNewLineで 
`RangeError (index): Invalid value: Only valid value is 0: -1` を発生させているユーザーがいたので、その対応
配列の参照時に添え字で0未満の数値が入るとエラーが出るので、0未満になりそうだったら早期returnを行う

isEndNewLineでエラーが発生しうるケースのハンドリング

---

packages/zefyr/lib/src/widgets/controller.dart
packages/zefyr/test/widgets/controller_test.dart

[improve(controller)最後の行から改行を消したい #112](https://github.com/hokutoresident/zefyr/pull/112)で対応した内容に対しての修正です。
以下のように内容が空の時にこの関数を走らせてしまうと``` Failed assertion: line 213 pos 12: 'firstChild != null': is not true.```とzefyr内部のエラーが発生してしまいます。ユーザー体験に特に影響はないです
（[スレッド](https://hokutohq.slack.com/archives/CL0STNCGG/p1725840002808899)）

improve(removeNewlineAtLast)空のZefyrに対して関数を走らせないように PRODUCT-1682
