hokutoresident/zefyr

- packages/zefyr/lib/src/widgets/editor.dart
> onTapImageの実装

- packages/zefyr/lib/src/widgets/editable_text_block.dart
- packages/zefyr/lib/src/widgets/editor.dart
https://www.notion.so/hokuto/5e402562ed614fe691150b7ac8bc9c70?v=9acbd05cb1b94d879da17ea1fe793f97&p=9d2bebcd679d4825833b245d1bb41c51
|before|after|
|-|-|
|![Simulator Screen Shot - iPhone SE (2nd generation) - 2021-05-16 at 15 07 44](https://user-images.githubusercontent.com/34063746/118635445-8e37b300-b80e-11eb-9fe4-008ea278db8f.png)|![Simulator Screen Shot - iPhone SE (2nd generation) - 2021-05-18 at 19 20 34](https://user-images.githubusercontent.com/34063746/118635465-94c62a80-b80e-11eb-8717-9fbd51a33348.png)|
> ブロックの数字を消す&padding調整

- packages/zefyr/lib/src/widgets/editable_text_block.dart
https://www.notion.so/hokuto/5e402562ed614fe691150b7ac8bc9c70?v=63bd086124a64e54902fc92e27d2e7ea&p=2a10a0f5d0c244a4bad0bff8909e37b6
> 箇条書きリストの点の位置がおかしい。数字つきリストは問題なし(デザイン確認してみる)

- packages/zefyr/lib/src/widgets/editor.dart
https://www.notion.so/hokuto/5e402562ed614fe691150b7ac8bc9c70?v=7cebecc0d0c141529ee44bd58b103378&p=500fce8244f04434ae5eddbb40f09e55
> 最後の改行がなくてもスクロールできるようにする（Noteアプリみたいにスペースを開ける）

- packages/zefyr/lib/src/widgets/editor.dart
Reverts hokutoresident/zefyr#20
> Revert "hokuto appの方で余白タップでの改行が動いてない"

- packages/zefyr/lib/src/widgets/controller.dart
https://www.notion.so/hokuto/053b1fe923cb4742b3e005d70c434064
https://user-images.githubusercontent.com/34063746/122375687-6ae35d80-cf9e-11eb-864c-30261c00fdc3.mov
> 本文最下部に見出し(箇条書き)を挿入すると改行ができない

- packages/notus/lib/src/document/attributes.dart
- packages/notus/test/document/attributes_test.dart
- packages/zefyr/lib/src/widgets/controller.dart
- packages/zefyr/lib/src/widgets/editor_toolbar.dart
- packages/zefyr/lib/src/widgets/text_line.dart
- packages/zefyr/lib/src/widgets/theme.dart
https://qiita.com/CUTBOSS/items/a96fb369e5d1d8eda0da
> マーカーの色変更(透明度10%) & rename

- packages/zefyr/lib/src/widgets/editor_input_client_mixin.dart
> 箇条書きの上で改行を2回行なって、バックスペースを押すとカーソルが消えて2回なにかしら入力しないと反応しなくなる

- packages/zefyr/lib/src/widgets/text_line.dart
try catchでお茶を濁した
https://www.notion.so/hokuto/b793c21fbc0b4d1e98f5f1a9a8d16137
> 編集時にグレーアウトすることがある問題

- packages/zefyr/lib/src/widgets/editable_text_block.dart
- packages/zefyr/lib/src/widgets/editor.dart
- packages/zefyr/lib/src/widgets/theme.dart
https://www.notion.so/24pt-24pt-2e9dfbd7c378475e9df242e91bf5053b
> インデントの幅を24pt > 28ptにした

- packages/zefyr/lib/src/widgets/editable_text_block.dart
||①が50以上のとき|
|-|-|
|![Simulator Screen Shot - iPhone 12 Pro - 2021-08-25 at 13 31 07](https://user-images.githubusercontent.com/34063746/130727173-a2134a4b-2d0b-43dc-a315-51aa243a331d.png)|![Simulator Screen Shot - iPhone 12 Pro - 2021-08-25 at 13 31 35](https://user-images.githubusercontent.com/34063746/130727204-1f4fd624-2c38-4773-aabf-6879acd43135.png)|
> 数字付き箇条書きのインデントに応じた①とか1)とかをつけるようにする

- packages/notus/lib/src/document/embeds.dart
- packages/zefyr/pubspec.yaml
https://github.com/hokutoresident/hokuto-app/pull/1206
のPRと対応
> 画像にoriginalSourceを追加できるようにした

- packages/zefyr/lib/src/widgets/controller.dart
https://www.notion.so/hokuto/5e402562ed614fe691150b7ac8bc9c70?v=9acbd05cb1b94d879da17ea1fe793f97&p=b5f2149c02404dada5e2e99a464526b1
> 見出し(小見出し)の文字列の途中で改行したときに無限ループ入って大量に開業される

- packages/zefyr/example/lib/src/home.dart
- packages/zefyr/lib/src/widgets/editor.dart
https://www.notion.so/hokuto/5e402562ed614fe691150b7ac8bc9c70?v=9acbd05cb1b94d879da17ea1fe793f97&p=4caad47da5bf402a98f2bde063f4f1d3
https://user-images.githubusercontent.com/34063746/132673311-8a64ac7e-ca62-47f0-8be5-310ef7bdb593.mov
> ノートでカーソルを当てた時スクロールするようにしたい

- .github/workflows/test_notus.yml
- .github/workflows/test_zefyr.yml
- packages/notus/.fvm/fvm_config.json
- packages/zefyr/.fvm/fvm_config.json
- packages/zefyr/example/ios/Flutter/AppFrameworkInfo.plist
- packages/zefyr/example/ios/Podfile.lock
- packages/zefyr/lib/src/services/keyboard.dart
- packages/zefyr/lib/src/widgets/editor.dart
`FocusNode.attach()`の`onKey`の返り値がboolから`KeyEventResult`に変わったので`KeyboardListener.handleKeyEvent()`の返り値だけ変更しました
android、iosでexampleで確認できる機能は一通り試しました
> Flutter2.5.2対応

- packages/zefyr/lib/src/widgets/controller.dart
最初の語句にスクロールする
[検索した後にノートを開いた時に該当キーワードがハイライトされているところまで飛ばしたい](https://www.notion.so/hokuto/5e402562ed614fe691150b7ac8bc9c70?v=9acbd05cb1b94d879da17ea1fe793f97&p=f7da2c323c5f401cba07f175128c1aa3)
> 最初の語句にスクロールする

- packages/zefyr/lib/src/widgets/controller.dart
- packages/zefyr/lib/src/widgets/text_line.dart
- packages/zefyr/lib/util.dart
- packages/zefyr/pubspec.yaml
- packages/zefyr/test/util_test.dart
https://www.notion.so/hokuto/5e402562ed614fe691150b7ac8bc9c70?v=090b35774add4b41b6825a1900212710&p=acc847f66d9d4381aca90b30e058661a
https://user-images.githubusercontent.com/34063746/144064589-4e4675e9-b3d3-4a99-8bdc-8dff033d5479.mov
> 英字の大文字小文字を無視して検索にヒットするように

- .github/workflows/milestone_check.yml
- マイルストーンのチェックの実装
- https://github.com/hokutoresident/hokuto-app/pull/1768 をコピペして、branchの部分と、secretsだけ書き換えた。
- マイルストーンが入っていない状態でマージされる(リリースが不明な変更が取り込まれる)のを防ぐため
-
> milestone check

- .github/workflows/test_notus.yml
- .github/workflows/test_zefyr.yml
- packages/zefyr/example/pubspec.yaml
- packages/zefyr/pubspec.yaml
- Update flutter version 2.5.2 to 2.8.0
- fix google_fonts version to 2.2.0 to avoid error
> ci: update flutter version

- .fvm/flutter_sdk
- .fvm/fvm_config.json
- .github/workflows/test_notus.yml
- .github/workflows/test_zefyr.yml
- packages/notus/.fvm/fvm_config.json
- packages/zefyr/.fvm/fvm_config.json
- packages/zefyr/example/ios/Podfile.lock
- packages/zefyr/example/ios/Runner/Info.plist
- packages/zefyr/example/lib/src/full_page.dart
- packages/zefyr/example/lib/src/home.dart
- packages/zefyr/example/lib/src/text_field_page.dart
- packages/zefyr/example/linux/flutter/generated_plugin_registrant.cc
- packages/zefyr/example/linux/flutter/generated_plugin_registrant.h
- packages/zefyr/example/linux/flutter/generated_plugins.cmake
- packages/zefyr/lib/src/widgets/editor.dart
- packages/zefyr/lib/src/widgets/text_selection.dart
- packages/zefyr/pubspec.yaml
- Flutter 2.8.0 -> 3.0.1に上げました
- canLaunch -> canLaunchUrlになっていたので変更しました
-
> Flutter 3.0.1

- packages/notus/lib/src/document/embeds.dart
- packages/zefyr/pubspec.yaml
zefyrでvideoのembedを処理できるようにしました
> allow embed video object

- packages/zefyr/lib/src/widgets/editor.dart
- packages/zefyr/lib/src/widgets/text_line.dart
- packages/zefyr/lib/src/widgets/theme.dart
WHAT
- 空行の高さを変更できるパラメータを追加
- height
- spacing
- 指定しない限り、デフォルト値が使用されます。
HOKUTOチケット：
https://www.notion.so/hokuto/87c479b51ee04ea497ba2d70b234461e?pvs=4
HOKUTOのPR：
https://github.com/hokutoresident/hokuto-app/pull/3970
context:
https://hokutohq.slack.com/archives/C068V2F8DSS/p1705481443658359?thread_ts=1705126297.330919&cid=C068V2F8DSS
> 空行の高さを変更できるパラメータを追加

- packages/zefyr/lib/src/rendering/editor.dart
- packages/zefyr/lib/src/widgets/controller.dart
- packages/zefyr/lib/src/widgets/editor.dart
コンテンツ内リンクの時は画面上部に移動、文字列検索の時は今まで通り画面中央に移動するよう修正
> 指定した文字列の箇所に移動する時、その箇所を画面の上部にするよう修正
